user  nginx;
worker_processes  auto;
events { worker_connections 1024; }

http {
    log_format monitor_combined escape=json
        '$time_local INFO [$http_x_trace_id] [nginx] [nginx:0] - access '
        '{'
            '"ts":"$time_local",'
            '"level":"INFO",'
            '"traceId":"$http_x_trace_id",'
            '"threadName":"nginx",'
            '"location":"nginx:0",'
            '"message":"access",'
            '"service":"nginx",'
            '"tradeType":"ss",'
            '"requestId":"$http_x_request_id",'
            '"remote_addr":"$remote_addr",'
            '"method":"$request_method",'
            '"path":"$uri",'
            '"status":$status,'
            '"request_time":"$request_time",'
            '"body_bytes_sent":$body_bytes_sent,'
            '"upstream_addr":"$upstream_addr",'
            '"upstream_time":"$upstream_response_time"'
        '}';

    upstream gateway {
        server gateway:8000;
    }

    server {
        listen 80;
        server_name _;

        access_log /var/log/nginx/access.log monitor_combined;

        location / {
            proxy_pass http://gateway;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Request-Id $http_x_request_id;
            proxy_set_header X-Trace-Id $http_x_trace_id;
        }
    }
}
